### ISSUE TITLE
Failed to activate the selection-counter package

### ISSUE THREAD

**Issue by yoniamir** [frabert/selection-counter#5]
Got this error when installing selection counter. This popped up right after the installation finished.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [selection-counter](https://github.com/frabert/selection-counter) package 1.0.0

### Stack Trace

Failed to activate the selection-counter package

```
At Cannot read property 'priority' of undefined

TypeError: Cannot read property 'priority' of undefined
    at StatusBarView.module.exports.StatusBarView.addLeftTile (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:55:136)
    at HTMLElement.SelectionCounterView.attach (/packages/selection-counter/lib/selection-counter-view.coffee:11:26)
    at Object.consumeStatusBar (/packages/selection-counter/lib/selection-counter.coffee:34:26)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:454:81)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -0:51.4.0 pane:show-next-item (input.hidden-input)
     -0:50.9.0 pane:show-previous-item (input.hidden-input)
  2x -0:50.4.0 pane:show-next-item (input.hidden-input)
  3x -0:49.4.0 pane:show-previous-item (div.package-detail.panels-item)
  2x -0:47.8.0 pane:show-next-item (input.hidden-input)
     -0:45.3.0 core:close (input.hidden-input)
  5x -0:37.6.0 core:move-up (input.hidden-input)
  6x -0:35.8.0 core:move-right (input.hidden-input)
     -0:34.9.0 find-and-replace:select-next (input.hidden-input)
  6x -0:34.2.0 core:move-up (input.hidden-input)
 12x -0:33.5.0 core:move-right (input.hidden-input)
  4x -0:32.3.0 find-and-replace:select-next (input.hidden-input)
     -0:26.1.0 editor:consolidate-selections (input.hidden-input)
     -0:24.8.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
auto-update-packages 1.0.1 
better-handlebars 0.1.1 
busy-signal 1.4.3 
copy-filepath-with-line-numbers 2.2.1 
cucumber 0.6.0 
editorconfig 2.2.2 
file-icons 2.1.13 
git-hide 1.0.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-gitignore 0.3.0 
language-procfile 0.1.1 
language-rspec 0.7.0 
language-swift 0.5.0 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-jshint 3.1.6 
linter-rubocop 2.2.0 
linter-sass-lint 1.8.3 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
railscast-theme 0.4.0 
ruby-test 1.0.2 
seeing-is-believing 2.2.3 
selection-counter 1.0.0 
sync-settings 0.8.3 
tabs-to-spaces 1.0.3 
zentabs 0.8.8 
```

**Comment by frabert** [comment]
Hi! Thanks for submitting the issue! I cannot reproduce this using Atom 1.20. I will try updating the editor

UPDATE: Sorry, the package installs on my 1.21.1 installation just fine... It's been a long time since I haven't done any atom development and unfortunately I do not have the time to track down package incompatibilities... You are welcome to give it a shot if you want! Sorry for the inconvenience...
